apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
        - name: storefront
          image: prinsoo/e-commerce:storefront
          ports:
            - containerPort: 4000
          env:
            - name: SERVER_API_HOST
              value: http://server
            - name: SERVER_API_PORT
              value: "3000"
            - name: SERVER_API_PATH
              value: shop-api
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: storefront
spec:
  selector:
    app: storefront
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
