apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: prinsoo/e-commerce:worker
          ports:
            - containerPort: 3000
          command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "run:server"]
          env:
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_PORT
              value: "5432"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
